local_costmap:
  transform_tolerance: 0.5
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.55
  publish_voxel_map: false
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.25
  origin_x: 0.0
  origin_y: 0.0
