"""autogenerated by genpy from dogsim/AdjustDogPositionGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class AdjustDogPositionGoal(genpy.Message):
  _md5sum = "e7afd226ddce08c69252f8908923bb2a"
  _type = "dogsim/AdjustDogPositionGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
geometry_msgs/PoseStamped dogPose
geometry_msgs/PointStamped goalPosition
geometry_msgs/PoseStamped futureDogPose
geometry_msgs/PointStamped futureGoalPosition

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/PointStamped
# This represents a Point with reference coordinate frame and timestamp
Header header
Point point

"""
  __slots__ = ['dogPose','goalPosition','futureDogPose','futureGoalPosition']
  _slot_types = ['geometry_msgs/PoseStamped','geometry_msgs/PointStamped','geometry_msgs/PoseStamped','geometry_msgs/PointStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dogPose,goalPosition,futureDogPose,futureGoalPosition

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AdjustDogPositionGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dogPose is None:
        self.dogPose = geometry_msgs.msg.PoseStamped()
      if self.goalPosition is None:
        self.goalPosition = geometry_msgs.msg.PointStamped()
      if self.futureDogPose is None:
        self.futureDogPose = geometry_msgs.msg.PoseStamped()
      if self.futureGoalPosition is None:
        self.futureGoalPosition = geometry_msgs.msg.PointStamped()
    else:
      self.dogPose = geometry_msgs.msg.PoseStamped()
      self.goalPosition = geometry_msgs.msg.PointStamped()
      self.futureDogPose = geometry_msgs.msg.PoseStamped()
      self.futureGoalPosition = geometry_msgs.msg.PointStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.dogPose.header.seq, _x.dogPose.header.stamp.secs, _x.dogPose.header.stamp.nsecs))
      _x = self.dogPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.dogPose.pose.position.x, _x.dogPose.pose.position.y, _x.dogPose.pose.position.z, _x.dogPose.pose.orientation.x, _x.dogPose.pose.orientation.y, _x.dogPose.pose.orientation.z, _x.dogPose.pose.orientation.w, _x.goalPosition.header.seq, _x.goalPosition.header.stamp.secs, _x.goalPosition.header.stamp.nsecs))
      _x = self.goalPosition.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d3I.pack(_x.goalPosition.point.x, _x.goalPosition.point.y, _x.goalPosition.point.z, _x.futureDogPose.header.seq, _x.futureDogPose.header.stamp.secs, _x.futureDogPose.header.stamp.nsecs))
      _x = self.futureDogPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.futureDogPose.pose.position.x, _x.futureDogPose.pose.position.y, _x.futureDogPose.pose.position.z, _x.futureDogPose.pose.orientation.x, _x.futureDogPose.pose.orientation.y, _x.futureDogPose.pose.orientation.z, _x.futureDogPose.pose.orientation.w, _x.futureGoalPosition.header.seq, _x.futureGoalPosition.header.stamp.secs, _x.futureGoalPosition.header.stamp.nsecs))
      _x = self.futureGoalPosition.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.futureGoalPosition.point.x, _x.futureGoalPosition.point.y, _x.futureGoalPosition.point.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.dogPose is None:
        self.dogPose = geometry_msgs.msg.PoseStamped()
      if self.goalPosition is None:
        self.goalPosition = geometry_msgs.msg.PointStamped()
      if self.futureDogPose is None:
        self.futureDogPose = geometry_msgs.msg.PoseStamped()
      if self.futureGoalPosition is None:
        self.futureGoalPosition = geometry_msgs.msg.PointStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.dogPose.header.seq, _x.dogPose.header.stamp.secs, _x.dogPose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dogPose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.dogPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.dogPose.pose.position.x, _x.dogPose.pose.position.y, _x.dogPose.pose.position.z, _x.dogPose.pose.orientation.x, _x.dogPose.pose.orientation.y, _x.dogPose.pose.orientation.z, _x.dogPose.pose.orientation.w, _x.goalPosition.header.seq, _x.goalPosition.header.stamp.secs, _x.goalPosition.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goalPosition.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.goalPosition.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.goalPosition.point.x, _x.goalPosition.point.y, _x.goalPosition.point.z, _x.futureDogPose.header.seq, _x.futureDogPose.header.stamp.secs, _x.futureDogPose.header.stamp.nsecs,) = _struct_3d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.futureDogPose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.futureDogPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.futureDogPose.pose.position.x, _x.futureDogPose.pose.position.y, _x.futureDogPose.pose.position.z, _x.futureDogPose.pose.orientation.x, _x.futureDogPose.pose.orientation.y, _x.futureDogPose.pose.orientation.z, _x.futureDogPose.pose.orientation.w, _x.futureGoalPosition.header.seq, _x.futureGoalPosition.header.stamp.secs, _x.futureGoalPosition.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.futureGoalPosition.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.futureGoalPosition.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.futureGoalPosition.point.x, _x.futureGoalPosition.point.y, _x.futureGoalPosition.point.z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.dogPose.header.seq, _x.dogPose.header.stamp.secs, _x.dogPose.header.stamp.nsecs))
      _x = self.dogPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.dogPose.pose.position.x, _x.dogPose.pose.position.y, _x.dogPose.pose.position.z, _x.dogPose.pose.orientation.x, _x.dogPose.pose.orientation.y, _x.dogPose.pose.orientation.z, _x.dogPose.pose.orientation.w, _x.goalPosition.header.seq, _x.goalPosition.header.stamp.secs, _x.goalPosition.header.stamp.nsecs))
      _x = self.goalPosition.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d3I.pack(_x.goalPosition.point.x, _x.goalPosition.point.y, _x.goalPosition.point.z, _x.futureDogPose.header.seq, _x.futureDogPose.header.stamp.secs, _x.futureDogPose.header.stamp.nsecs))
      _x = self.futureDogPose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7d3I.pack(_x.futureDogPose.pose.position.x, _x.futureDogPose.pose.position.y, _x.futureDogPose.pose.position.z, _x.futureDogPose.pose.orientation.x, _x.futureDogPose.pose.orientation.y, _x.futureDogPose.pose.orientation.z, _x.futureDogPose.pose.orientation.w, _x.futureGoalPosition.header.seq, _x.futureGoalPosition.header.stamp.secs, _x.futureGoalPosition.header.stamp.nsecs))
      _x = self.futureGoalPosition.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3d.pack(_x.futureGoalPosition.point.x, _x.futureGoalPosition.point.y, _x.futureGoalPosition.point.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.dogPose is None:
        self.dogPose = geometry_msgs.msg.PoseStamped()
      if self.goalPosition is None:
        self.goalPosition = geometry_msgs.msg.PointStamped()
      if self.futureDogPose is None:
        self.futureDogPose = geometry_msgs.msg.PoseStamped()
      if self.futureGoalPosition is None:
        self.futureGoalPosition = geometry_msgs.msg.PointStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.dogPose.header.seq, _x.dogPose.header.stamp.secs, _x.dogPose.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.dogPose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.dogPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.dogPose.pose.position.x, _x.dogPose.pose.position.y, _x.dogPose.pose.position.z, _x.dogPose.pose.orientation.x, _x.dogPose.pose.orientation.y, _x.dogPose.pose.orientation.z, _x.dogPose.pose.orientation.w, _x.goalPosition.header.seq, _x.goalPosition.header.stamp.secs, _x.goalPosition.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goalPosition.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.goalPosition.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.goalPosition.point.x, _x.goalPosition.point.y, _x.goalPosition.point.z, _x.futureDogPose.header.seq, _x.futureDogPose.header.stamp.secs, _x.futureDogPose.header.stamp.nsecs,) = _struct_3d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.futureDogPose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.futureDogPose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 68
      (_x.futureDogPose.pose.position.x, _x.futureDogPose.pose.position.y, _x.futureDogPose.pose.position.z, _x.futureDogPose.pose.orientation.x, _x.futureDogPose.pose.orientation.y, _x.futureDogPose.pose.orientation.z, _x.futureDogPose.pose.orientation.w, _x.futureGoalPosition.header.seq, _x.futureGoalPosition.header.stamp.secs, _x.futureGoalPosition.header.stamp.nsecs,) = _struct_7d3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.futureGoalPosition.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.futureGoalPosition.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.futureGoalPosition.point.x, _x.futureGoalPosition.point.y, _x.futureGoalPosition.point.z,) = _struct_3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d3I = struct.Struct("<3d3I")
_struct_3I = struct.Struct("<3I")
_struct_7d3I = struct.Struct("<7d3I")
_struct_3d = struct.Struct("<3d")
